# Site settings
title: Paso Libre
email: 
description: > # this means to ignore newlines until "baseurl:"
  Paso Libre ist eine Tanz-Formation und Show-Gruppe spezialisiert auf Salsa und Bachata. 
  Wir bieten Shows für jeden Event, wie etwa für Geburtstage, Hochzeiten oder Straßenfeste.
  Wir freuen uns auf Ihre Anfrage!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pasolibre.de" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
